
server:
  port: 8082

logging:
  level:
    org.springframework: DEBUG

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LWluc3BqdC1pbnN0Z32ruqeriwuriuofasjvzxlkfjaosdjfxlguoisdufojsdlfkjsdofjoxiv

file:
  path:
    deleted-user: C:/Users/hanth/OneDrive/Desktop/Personal/deleted-user.txt

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/personal?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: dbm
    password: rhksflwk123@
  jpa:
    show-sql: true
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        globally_quoted_identifiers: true